-- =============================================
-- Creator Hub — Trevaos DB Tables
-- =============================================
-- These tables live in the main Trevaos Supabase project.
-- See: Treva-backend/supabase/migrations/037_creator_hub_tables.sql
--
-- Base table `creator_profiles` is from migration 009.
-- Hub-specific columns (username, tagline, etc.) added by migration 037.
--
-- Table mapping (old standalone → Trevaos):
--   users               → creator_profiles (auth_user_id, display_name as name, base_city as location)
--   social_accounts     → creator_social_accounts
--   dashboard_modules   → creator_dashboard_modules
--   carousel_images     → creator_carousel_images
--   collab_brands       → creator_collab_brands
--   deals               → creator_hub_deals
--   accepted_deals      → creator_hub_accepted_deals
--   messages            → creator_hub_messages
--   oauth_tokens        → creator_oauth_tokens
--   Storage bucket      → creator-assets (same name)
--
-- On signup, also insert into org_users with role_type = 'creator'.
